### ISSUE TITLE
plinio.PIT not found

### ISSUE THREAD

**Issue by Mojtaba1515** [eml-eda/plinio#7]
In the readme file, it is mentioned to use plinio.PIT to utilize the package. However, when I import plinio and attempt to use plinio.PIT, I encounter an error: "module 'plinio' has no attribute 'PIT'." I am seeking guidance on resolving this issue. Could you please advise me on the correct way to import plinio?

**Comment by matteorisso** [comment]
Dear @Mojtaba1515,
As you can see in [README](https://github.com/eml-eda/plinio/blob/main/plinio/methods/pit/README.md) of PIT you can import the `PIT` method with `from plinio.method import PIT` then you can use directly the `PIT` class (instead of `plinio.PIT`) to transform your model and do NAS on it. Please let me know if this solve your problem.

P.S., you are right that in some points of the README `plinio.PIT` it is used. This is an inconsistency from a previous version. I will proceed to fix the README. Thank you very much for pointing out the issue!
